### ISSUE TITLE
Flesh out the menu

### ISSUE THREAD

**Issue by VagishVela** [VagishVela/project-pygames#14]
~If https://github.com/VagishVela/project-pygames/pull/12 is merged then work off dev if not work off https://github.com/VagishVela/project-pygames/pull/12 in a new branch.~

- [x] clear the debugging stuff

**Comment by ificiana** [comment]
Bug: `it requires multiple clicks to pass event.type == pygame.MOUSEBUTTONDOWN because it doesn't always register that event type`

**Comment by ificiana** [comment]
If #24 is merged then work off dev if not work off #24 in a new branch.
